baseURL = 'https://gustoliveira.github.io/personal-site/'
languageCode = 'en-us'
title = 'Gustavo de Oliveira Ferreira'

theme = 'blank'

[params]
  description = 'Software Engineer and Computer Science Student sharing insights on algorithms, mobile development, and software engineering.'
  author = 'Gustavo de Oliveira Ferreira'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

